image: python:3.8  # Nutzt das Python 3.8 Docker-Image

stages:
  - build
  - test
  - lint
  - deploy

build-job:
  stage: build
  script:
    - echo "Building application..."
    - cd python_Calculator
    - pip install -r requirements.txt  # Anforderungen installieren

unit-test-job:
  stage: test
  script:
    - echo "Installing dependencies..."
    - cd python_Calculator
    - pip install pytest
    - echo "Running unit tests..."
    - pytest --junitxml=report.xml
  artifacts:
    when: always
    paths:
      - python_Calculator/report.xml

lint-job:
  stage: lint
  script:
    - echo "Running Linting..."
    - cd python_Calculator
    - pip install pylint
    - pylint calculator.py test_calculator.py --output-format=text > pylint-report.txt || true
  artifacts:
    when: always
    paths:
      - python_Calculator/pylint-report.txt

deploy-job:
  stage: deploy
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
