name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r python_Calculator/requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run Unit Tests
      run: |
        python -m unittest discover -s python_Calculator

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: python_Calculator/test_results.out

    # Install Node.js (falls nicht bereits vorhanden)
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    # Snyk Security Test
    - name: Install Snyk CLI
      run: |
        npm install -g snyk

    - name: Authenticate Snyk
      run: |
        snyk auth ${{ secrets.SNYK_TOKEN }}

    - name: Run Snyk Test
      run: |
        snyk test --package-manager=pip --file=python_Calculator/requirements.txt --severity-threshold=medium
