name: Python CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: python:3.8

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install dependencies (Build Stage)
      run: |
        echo "Building application..."
        cd python_Calculator
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  test:
    needs: build
    runs-on: ubuntu-20.04
    container:
      image: python:3.8

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install dependencies for testing
      run: |
        echo "Installing dependencies for testing..."
        cd python_Calculator
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run Unit Tests
      run: |
        echo "Running unit tests..."
        cd python_Calculator
        pytest --junitxml=report.xml

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: python_Calculator/report.xml

  lint:
    needs: test
    runs-on: ubuntu-20.04
    container:
      image: python:3.8

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install dependencies for linting
      run: |
        echo "Installing dependencies for linting..."
        cd python_Calculator
        python -m pip install --upgrade pip
        pip install pylint

    - name: Run Linting
      run: |
        echo "Running Linting..."
        cd python_Calculator
        pylint calculator.py test_calculator.py --output-format=text > pylint-report.txt || true

    - name: Upload Lint Report
      uses: actions/upload-artifact@v3
      with:
        name: pylint-report
        path: python_Calculator/pylint-report.txt

  deploy:
    needs: [build, test, lint]
    runs-on: ubuntu-20.04
    container:
      image: python:3.8

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy Application
      run: |
        echo "Deploying application..."
        echo "Application successfully deployed."
